name: Build and Release WPF Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the project
      run: dotnet publish -c Release -r win-x64 --self-contained

    - name: Create Release Directory
      run: mkdir release

    - name: Copy Published Files
      run: |
        ls \a\brawlhalla-ping-checker\brawlhalla-ping-checker\brawlhalla-ping-checker

  # xcopy /s /y "brawlhalla-ping-checker\bin\Release\net8.0-windows\publish\win-x64\brawlhalla-ping-checker.exe" ".\release"
      
  #   - name: Upload Release Artifact
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: brawlhalla-ping-checker
  #       path: release/

  # release:
  #   needs: build
  #   runs-on: windows-latest
  #   steps:
  #   - name: Download Release Artifact
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: brawlhalla-ping-checker

  #   - name: Create GitHub Release
  #     uses: softprops/action-gh-release@v1
  #     with:
  #       files: release/**
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
